version: '3.7'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root      
    volumes:
      - /home/mysql/data:/var/lib/mysql
  

  spring_app:
    image: "achatproject"
    container_name: achatproject
    restart: unless-stopped
    ports:
      - 9090:9090
    depends_on:
      - mysqldb